branches:
  only:
    - master

language: php

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

install:
  - npm install phplint
  - composer install

script:
  - phplint '*.php' 'lib/**/*.php' 'fixtures/**/*.php' --suppress
